FROM alpine:latest

LABEL maintainer="sn0b4ll"

COPY 500retry.patch /home/

COPY slowretry.patch /home/

COPY removeconnlimit.patch /home/

RUN apk add --update --no-cache bash tor tzdata privoxy vim nginx nginx-mod-stream autoconf build-base binutils cmake file gcc g++ git libgcc gmp libtool make musl musl-dev gnutls gnutls-dev nettle libssh2 libssh2-dev libc-dev ca-certificates c-ares c-ares-dev libxml2 libxml2-dev sqlite-libs sqlite-dev pkgconfig automake cppunit cppunit-dev util-macros gettext gettext-dev zlib zlib-dev \
&& git clone https://github.com/aria2/aria2.git /home/aria2 && patch /home/aria2/src/HttpSkipResponseCommand.cc < /home/500retry.patch && patch /home/aria2/src/DownloadCommand.cc < /home/slowretry.patch && patch /home/aria2/src/OptionHandlerFactory.cc < /home/removeconnlimit.patch && rm -f /home/500retry.patch && rm -f /home/slowretry.patch && rm -f /home/removeconnlimit.patch && cd /home/aria2 && autoreconf -i && ./configure && make && make install && rm -rf /home/aria2 \
&& apk del autoconf build-base binutils cmake file gcc g++ git libtool make musl-dev gnutls-dev libssh2-dev c-ares-dev libxml2-dev sqlite-dev pkgconfig automake cppunit-dev util-macros gettext-dev zlib-dev

CMD ["/run/run_aria2.sh"]

